# Generated by Django 5.2.5 on 2025-12-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loans',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='monthly_loan_payment',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
