# Generated by Django 4.2.27 on 2026-01-02 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmonth',
            old_name='payment',
            new_name='total',
        ),
    ]
