# Generated by Django 4.2.27 on 2026-01-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krd', '0002_rename_payment_paymentmonth_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmonth',
            name='payment',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
