# Generated by Django 4.2.27 on 2026-01-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krd', '0003_paymentmonth_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='amount_paid',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
