# Generated by Django 4.2.27 on 2026-01-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krd', '0004_loan_amount_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='amount_paid',
            new_name='paid_amount',
        ),
    ]
