# Generated by Django 4.2.27 on 2025-12-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krd', '0005_alter_client_passport_pinfl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='amount',
            new_name='payment',
        ),
        migrations.AddField(
            model_name='loan',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], default='male', max_length=30),
        ),
    ]
