# Generated by Django 4.2.27 on 2026-01-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krd', '0005_rename_amount_paid_loan_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='paid_amount',
        ),
        migrations.AddField(
            model_name='paymentmonth',
            name='paid_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
