# Generated by Django 4.2.27 on 2025-12-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krd', '0006_rename_amount_loan_payment_loan_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='term',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('done', 'berildi'), ('approved', 'tasdiqlandi'), ('rejected', 'rad etildi'), ('pending', 'jarayonda'), ('paid', 'yopilgan')], default='pending', max_length=50),
        ),
    ]
