# Generated by Django 6.0.1 on 2026-01-11 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krd', '0007_alter_loan_payday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmonth',
            name='paid_date',
        ),
        migrations.AlterField(
            model_name='loan',
            name='payday',
            field=models.PositiveIntegerField(default=11),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='krd.loan')),
            ],
        ),
    ]
