# Generated by Django 6.0.1 on 2026-01-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krd', '0010_alter_paymentmonth_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmonth',
            name='paid_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
